services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_agencia_viajes
      MYSQL_USER: viajes_user
      MYSQL_PASSWORD: Sa18Zs21!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  mysql_data: